# Override containers for local / dev environnement
version: "2.4"
services:
  reverse_proxy:
    volumes:
      - mnaprojectname_nginx_data:/data:z
      - ./reverse_proxy/dev/includes:/etc/nginx/templates/includes/env

  ui:
   ui:
    mem_limit: 1g
    stdin_open: true
    volumes:
      - ./ui:/app:z
      - /app/.next
      - /app/node_modules
    build:
      context: ui
      dockerfile: Dockerfile.dev
      args:
        - NEXT_PUBLIC_ENV=dev
        - NEXT_PUBLIC_BASE_URL=http://localhost
        - NEXT_PUBLIC_BASE_HOST=localhost
        - NEXT_PUBLIC_METABASE_URL=https://mnaprojectname.mnaDNSBASE/
        - NEXT_PUBLIC_METABASE_SECRET_KEY=
        - SKIP_PREFLIGHT_CHECK=true

  server:
    command: ["yarn", "debug"]
    ports:
      - "127.0.0.1:9229:9229" # Allows remote debugging
    volumes:
      - ./server/src:/app/src:z # Allows source folders to be watched
      - ./server/config:/app/config:z
      - mnaprojectname_server_data:/data:z
    environment:
      - MNAPROJECTNAME_ENV=dev
      - MNAPROJECTNAME_LOG_LEVEL=debug
      - MNAPROJECTNAME_LOG_DESTINATIONS=stdout,mongodb
      - MNAPROJECTNAME_SMTP_HOST=smtp
      - MNAPROJECTNAME_SMTP_PORT=1025
    depends_on:
      - smtp

  mongodb:
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - mnaprojectname_mongodb_data:/data:z

  smtp:
    image: mailhog/mailhog
    container_name: mnaprojectname_smtp
    mem_limit: 128m
    ports:
      - 1025:1025
    networks:
      - mnaprojectname_network
    environment:
      - MH_UI_WEB_PATH=smtp

volumes:
  mnaprojectname_mongodb_data:
    driver: local
    name: mnaprojectname_mongodb_data
  mnaprojectname_nginx_data:
    driver: local
    name: mnaprojectname_nginx_data
  mnaprojectname_server_data:
    driver: local
    name: mnaprojectname_server_data
