# Override containers for local / dev environnement
version: "2.4"
services:
  reverse_proxy:
    volumes:
      - mnaprojectname_nginx_data:/data

  ui:
    command: yarn start
    mem_limit: 1g
    stdin_open: true
    volumes:
      - ./ui:/app #Allows source folders to be watched
      - /app/node_modules/

  server:
    command: [ "yarn", "debug" ]
    ports:
      - "127.0.0.1:9229:9229" # Allows remote debugging
    volumes:
      - ./server/src:/app/src # Allows source folders to be watched
      - ./server/config:/app/config
      - mnaprojectname_server_data:/data
    environment:
      - mnaprojectname_ENV=dev
      - mnaprojectname_LOG_LEVEL=debug

  mongodb:
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - mnaprojectname_mongodb_data:/data

  elasticsearch:
    ports:
      - "127.0.0.1:9200:9200"
    volumes:
      - mnaprojectname_data_elasticsearch:/usr/share/elasticsearch/data

  kibana:
    ports:
      - "127.0.0.1:5601:5601"

volumes:
  mnaprojectname_data_elasticsearch:
    driver: local
    name: mnaprojectname_data_elasticsearch
  mnaprojectname_mongodb_data:
    driver: local
    name: mnaprojectname_mongodb_data
  mnaprojectname_nginx_data:
    driver: local
    name: mnaprojectname_nginx_data
  mnaprojectname_server_data:
    driver: local
    name: mnaprojectname_server_data
