version: "2.4"
services:
  reverse_proxy:
    image: mnaprojectname_reverse_proxy
    container_name: mnaprojectname_reverse_proxy
    build:
      context: reverse_proxy
    mem_limit: 256m
    restart: unless-stopped
    ports:
      - 80:80
    networks:
      - mnaprojectname_network
    depends_on:
      - server
      - ui

  ui:
    image: mnaprojectname_ui
    container_name: mnaprojectname_ui
    build:
      context: ui
    mem_limit: 256m
    networks:
      - mnaprojectname_network
    depends_on:
      - server

  server:
    image: mnaprojectname_server
    container_name: mnaprojectname_server
    build:
      context: server
    mem_limit: 1g
    restart: unless-stopped
    networks:
      - mnaprojectname_network
    depends_on:
      - mongodb
    environment:
      - MNAPROJECTNAME_MONGODB_URI=mongodb://mongodb:27017/mnaprojectname?retryWrites=true&w=majority
      - MNAPROJECTNAME_ELASTICSEARCH_NODE=http://elasticsearch:9200
      - MNAPROJECTNAME_LOG_DESTINATIONS=stdout,mongodb

  mongodb:
    image: mongo:5.0.2-focal
    container_name: mnaprojectname_mongodb
    mem_limit: 1g
    restart: unless-stopped
    networks:
      - mnaprojectname_network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.1.1
    container_name: mnaprojectname_elasticsearch
    environment:
      - ES_JAVA_OPTS=-Xmx512m -Xms512m
      - cluster.name=docker-cluster
      - discovery.type=single-node
      - discovery.zen.minimum_master_nodes=1
      - network.host=0.0.0.0
    mem_limit: 1g
    networks:
      - mnaprojectname_network

  kibana:
    image: docker.elastic.co/kibana/kibana-oss:7.1.1
    container_name: mnaprojectname_kibana
    depends_on:
      - elasticsearch
    networks:
      - mnaprojectname_network
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
networks:
  mnaprojectname_network:
    name: mnaprojectname_network
