services:
  mongodb:
    build: ./.infra/local/
    restart: unless-stopped
    hostname: mongodb
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - tpml_mongodb_data:/data
    healthcheck:
      test: ["CMD", "mongosh", "--eval", '''db.runCommand("ping").ok''', "--quiet"]
      interval: 10s
      timeout: 5s
      retries: 12
      start_period: 10s

  smtp:
    image: axllent/mailpit:latest
    restart: unless-stopped
    ports:
      - 1025:1025
      - 8025:8025
    environment:
      - MP_DATA_FILE=/data/mailpit.db
    volumes:
      - tpml_smtp_data:/data

volumes:
  tpml_mongodb_data:
    driver: local
    name: tpml_mongodb_data
  tpml_smtp_data:
    driver: local
    name: tpml_smtp_data
