version: "2.4"
services:
  reverse_proxy:
    image: template_app_reverse_proxy
    container_name: template_app_reverse_proxy
    build:
      context: reverse_proxy
    mem_limit: 256m
    restart: unless-stopped
    ports:
      - 80:80
    networks:
      - template_app_network
    depends_on:
      - server

  ui:
    image: template_app_ui
    container_name: template_app_ui
    build:
      context: ui
    mem_limit: 256m
    networks:
      - template_app_network
    depends_on:
      - server

  server:
    image: template_app_server
    container_name: template_app_server
    build:
      context: server
    mem_limit: 1g
    restart: unless-stopped
    networks:
      - template_app_network
    depends_on:
      - mongodb
    environment:
      - TEMPLATE_APP_MONGODB_URI=mongodb://mongodb:27017/template-app?retryWrites=true&w=majority

  mongodb:
    image: mongo:4.2.6-bionic
    container_name: template_app_mongodb
    mem_limit: 1g
    restart: unless-stopped
    networks:
      - template_app_network

networks:
  template_app_network:
    name: template_app_network
