# Override containers for local / dev environnement
version: "2.4"
services:
  reverse_proxy:
    volumes:
      - template_app_nginx_data:/data

  ui:
    command: yarn start
    mem_limit: 1g
    stdin_open: true
    volumes:
      - ./ui:/app #Allows source folders to be watched

  server:
    command: ["yarn", "debug"]
    ports:
      - "127.0.0.1:9229:9229" # Allows remote debugging
    volumes:
      - ./server/src:/app/src # Allows source folders to be watched
      - ./server/config:/app/config
      - template_app_server_data:/data
    environment:
      - TEMPLATE_APP_ENV=dev
      - TEMPLATE_APP_LOG_LEVEL=debug

  mongodb:
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - template_app_mongodb_data:/data

  elasticsearch:
    ports:
      - "127.0.0.1:9200:9200"
    volumes:
      - template_app_data_elasticsearch:/usr/share/elasticsearch/data
      - ./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro

  kibana:
    ports:
      - "127.0.0.1:5601:5601"
    volumes:
      - ./elasticsearch/kibana.yml:/usr/share/kibana/config/kibana.yml:ro

volumes:
  template_app_data_elasticsearch:
    driver: local
    name: template_app_data_elasticsearch
  template_app_mongodb_data:
    driver: local
    name: template_app_mongodb_data
  template_app_nginx_data:
    driver: local
    name: template_app_nginx_data
  template_app_server_data:
    driver: local
    name: template_app_server_data
