version: "2.4"
services:
  reverse_proxy:
    image: mnaprojectname_reverse_proxy
    container_name: mnaprojectname_reverse_proxy
    build:
      context: reverse_proxy
    mem_limit: 256m
    restart: unless-stopped
    ports:
      - 80:80
    networks:
      - mnaprojectname_network
    depends_on:
      - server
      - ui
    environment:
      - PARANOIA=1
      - ANOMALY_INBOUND=5
      - ANOMALY_OUTBOUND=4
      - REPORTING_LEVEL=4
      - DNS_SERVER=127.0.0.11
      - PROXY=1
      - SERVERNAME=localhost
      - ACCESSLOG=/data/access.log
      - ERRORLOG=/data/error.log
      - LOGLEVEL=warn
      - NGINX_ALWAYS_TLS_REDIRECT=false
      - ALLOWED_METHODS=GET HEAD POST OPTIONS PUT DELETE

  ui:
    image: mnaprojectname_ui
    container_name: mnaprojectname_ui
    build:
      context: ui
    mem_limit: 256m
    networks:
      - mnaprojectname_network
    depends_on:
      - server
    environment:
      - SERVER_URI=http://server:5000

  server:
    image: mnaprojectname_server
    container_name: mnaprojectname_server
    build:
      context: server
    mem_limit: 1g
    restart: unless-stopped
    networks:
      - mnaprojectname_network
    depends_on:
      - mongodb
    environment:
      - MNAPROJECTNAME_MONGODB_URI=mongodb://mongodb:27017/mnaprojectname?retryWrites=true&w=majority
      - MNAPROJECTNAME_LOG_DESTINATIONS=stdout,mongodb

  mongodb:
    image: mongo:5.0.6-focal
    container_name: mnaprojectname_mongodb
    mem_limit: 2g
    restart: unless-stopped
    networks:
      - mnaprojectname_network

networks:
  mnaprojectname_network:
    name: mnaprojectname_network
