version: "2.4"
services:
  reverse_proxy:
    image: mnaprojectname_reverse_proxy
    container_name: mnaprojectname_reverse_proxy
    build:
      context: reverse_proxy
    mem_limit: 256m
    restart: unless-stopped
    ports:
      - 80:80
    networks:
      - mnaprojectname_network
    depends_on:
      - server
      - ui

  ui:
    image: mnaprojectname_ui
    container_name: mnaprojectname_ui
    build:
      context: ui
    mem_limit: 256m
    networks:
      - mnaprojectname_network
    depends_on:
      - server

  server:
    image: mnaprojectname_server
    container_name: mnaprojectname_server
    build:
      context: server
    mem_limit: 1g
    restart: unless-stopped
    networks:
      - mnaprojectname_network
    depends_on:
      - mongodb
    environment:
      - MNAPROJECTNAME_MONGODB_URI=mongodb://mongodb:27017/mnaprojectname?retryWrites=true&w=majority
      - MNAPROJECTNAME_LOG_DESTINATIONS=stdout,mongodb

  mongodb:
    image: mongo:5.0.2-focal
    container_name: mnaprojectname_mongodb
    mem_limit: 1g
    restart: unless-stopped
    networks:
      - mnaprojectname_network

networks:
  mnaprojectname_network:
    name: mnaprojectname_network
