# Override containers for local / dev environnement
version: "2.4"
services:
  reverse_proxy:
    volumes:
      - mnaprojectname_nginx_data:/data
    build:
      args:
        - ENV=development

  ui:
    build:
      context: ui
      dockerfile: Dockerfile.dev
    # env_file: ./ui/.env
    volumes:
      - ./ui:/app
      - /app/node_modules
      - /app/.next
    mem_limit: 1g
    stdin_open: true

  server:
    command: ["yarn", "debug"]
    ports:
      - "127.0.0.1:9229:9229" # Allows remote debugging
    volumes:
      - ./server/src:/app/src # Allows source folders to be watched
      - ./server/config:/app/config
      - mnaprojectname_server_data:/data
    environment:
      - MNAPROJECTNAME_ENV=dev
      - MNAPROJECTNAME_LOG_LEVEL=debug

  mongodb:
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - mnaprojectname_mongodb_data:/data

volumes:
  mnaprojectname_mongodb_data:
    driver: local
    name: mnaprojectname_mongodb_data
  mnaprojectname_nginx_data:
    driver: local
    name: mnaprojectname_nginx_data
  mnaprojectname_server_data:
    driver: local
    name: mnaprojectname_server_data
