- name: Stoppe tous les conteneurs applicatifs
  shell: "bash /opt/mnaprojectname/stop-app.sh"

- name: "Clone du repository (branche : {{ git_revision }})"
  git:
    repo: "https://github.com/mission-apprentissage/mnaREPOname.git"
    version: "{{ git_revision }}"
    force: yes
    accept_hostkey: yes
    dest: /opt/mnaprojectname/repository

- name: Création des répertoires 'overrides'
  file:
    path: "/opt/mnaprojectname/.overrides/{{ item.path }}/"
    state: directory
  with_filetree:
    - app/.overrides/common/
    - app/.overrides/{{ env_type }}/
  when: item.state == 'directory'

- name: Copie des fichiers 'overrides'
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "/opt/mnaprojectname/.overrides/{{ item.path }}"
  with_filetree:
    - app/.overrides/common/
    - app/.overrides/{{ env_type }}/
  when: item.state == 'file' and ".DS_Store" not in item.path

- name: Root only pour tous les répertoires applicatifs
  file:
    path: "{{item}}"
    state: directory
    owner: root
    group: root
    mode: 770
  with_items:
    - "/opt/mnaprojectname/tools"
    - "/opt/mnaprojectname/repository"
    - "/opt/mnaprojectname/data"
    - "/opt/mnaprojectname/backups"
    - "/opt/mnaprojectname/.overrides"

- name: Add cron to rotate nginx files
  ansible.builtin.cron:
    name: "rotate_nginx_log_files"
    minute: "0"
    hour: "1"
    job: "bash /opt/mnaprojectname/tools/rotate-nginx-log-files.sh >> /var/log/cron.log 2>&1"

- name: Add cron to reload app automatically
  when: env_type == "recette"
  ansible.builtin.cron:
    name: "reload-app"
    minute: "*/1"
    hour: 8-20
    weekday: 1-5
    job: "bash /opt/mnaprojectname/reload-app.sh >> /var/log/cron.log 2>&1"
