- name: Stop all previous started docker containers
  shell: "docker container stop $(docker container ls -q --filter name=template*) || true"

- name: Remove repository
  file:
    path: /opt/mna/template
    state: absent

- name: "Clone repository and checkout branch {{ git_revision }}"
  git:
    repo: "git@github.com:mission-apprentissage/template-apprentissage.git"
    version: "{{ git_revision }}"
    force: yes
    accept_hostkey: yes
    dest: /opt/mna/template

- name: Create data directory
  file:
    path: /opt/mna/data
    state: directory

- name: Prevent other users to read sensible files
  file:
    path: "{{item}}"
    state: directory
    mode: o-rwx
  with_items:
    - "/opt/mna/template"
    - "/opt/mna/data"

- name: Copy scripts
  copy:
    src: opt/mna/
    dest: /opt/mna
    group: mna

- name: Set all scripts as executable for 'mna' group
  shell: "chmod g+x /opt/mna/*.sh"

- name: Allow 'start-app.sh' to be ran by 'mna' group
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: "{{item}}"
    line: "%mna        ALL=(ALL)       NOPASSWD: {{item}}"
  with_items:
    - "/opt/mna/start-app.sh"

- name: Generate SSL certificate
  shell: "bash /opt/mna/template/.infra/azure/ssl/generate-certificate.sh {{dns_name}}"
  register: output

- debug:
    var: output
