- name: Ensure os is up to date
  shell: apt-get -y update

- name: Upgrade system packages
  shell: apt-get -y upgrade

- include_role:
    name: geerlingguy.docker

- name: Check if ctop binary is already installed
  stat: path=/usr/local/bin/ctop
  register: ctop

- name: Install ctop binary
  when: ctop.stat.exists == False
  shell: "wget https://github.com/bcicen/ctop/releases/download/v0.7.1/ctop-0.7.1-linux-amd64 -O /usr/local/bin/ctop && chmod +x /usr/local/bin/ctop"

- name: Install apt packages
  apt:
    name: ['vim', 'htop', 'jq', 'git']
