- import_tasks: install-dependencies.yml

- import_tasks: configure-sshd.yml

- import_tasks: configure-root.yml

- include: create-sudoer-user.yml
  with_items:
    - {
        username: "sbenfares",
        authorized_key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDsVhnNZThQdvRJR0TN5c2AVRgaDKDi4Ots22vQb0RRVmb/ygrzZJB4u/LRriTdjGmpm8GEHew2f2WE3AhCi1ml4Z5LovYlv1diKEjwUHv63fJdNcyMm0TUhpvFNLSJIsNKsawc+e3hmI1sI1i/uEV9UdcUpqjJ6iL9NCJ029dPhokDZXC2Sj3XhPWjqvamxgzuakuZWZHPbQYxKVcrEpMQ0SratOpVPK+coK3xF+AdIYHYogyueWjA9mfdVNa59DyTaOdgUkT+UNHlAiSnEzebhcKHQk5ZxAXMX9JW0lofx7S4uShbwKpbR83MpjhoTIZ2uorBjrs2+OXkp7h1E8Cj Samir@PC-DELL-CTO",
      }

- import_tasks: install-app.yml
