#Override containers for azure environments
version: "2.4"
services:
  reverse_proxy:
    ports:
      - 443:443
    volumes:
      - /opt/mna/data/nginx:/data
      - /opt/mna/template/.infra/azure/reverse_proxy/nginx-azure-server.conf:/etc/nginx/conf.d/nginx-azure-server.conf:ro
      - /opt/mna/data/ssl:/ssl:ro

  server:
    volumes:
      - /opt/mna/data/server:/data
    environment:
      - TEMPLATE_ENV=azure
      - TEMPLATE_LOG_LEVEL=info
      - TEMPLATE_PUBLIC_URL=https://mna-template.francecentral.cloudapp.azure.com

  fail2ban_containers:
    #Protects containers by adding rules into DOCKER-USER table
    image: crazymax/fail2ban
    container_name: template_fail2ban_containers
    network_mode: host
    depends_on:
      - reverse_proxy
    cap_add:
      - NET_ADMIN
    volumes:
      - /opt/mna/template/.infra/azure/fail2ban/action.d:/data/action.d:ro
      - /opt/mna/template/.infra/azure/fail2ban/filter.d:/data/filter.d:ro
      - /opt/mna/template/.infra/azure/fail2ban/jail.d/vsftpd.local:/data/jail.d/vsftpd.local:ro
      - /opt/mna/template/.infra/azure/fail2ban/jail.d/nginx.local:/data/jail.d/nginx.local:ro
      - /opt/mna/data/nginx:/nginx
    environment:
      - F2B_LOG_TARGET=STDOUT
      - F2B_LOG_LEVEL=DEBUG
      - F2B_DB_PURGE_AGE=1d
      - F2B_IPTABLES_CHAIN=DOCKER-USER

  fail2ban_system:
    #Protects system by adding rules into global INPUT table
    image: crazymax/fail2ban
    container_name: template_fail2ban_system
    network_mode: host
    cap_add:
      - NET_ADMIN
    volumes:
      - /opt/mna/template/.infra/azure/fail2ban/action.d:/data/action.d:ro
      - /opt/mna/template/.infra/azure/fail2ban/filter.d:/data/filter.d:ro
      - /opt/mna/template/.infra/azure/fail2ban/jail.d/sshd.local:/data/jail.d/sshd.local:ro
      - /var/log:/system
    environment:
      - F2B_LOG_TARGET=STDOUT
      - F2B_LOG_LEVEL=DEBUG
      - F2B_DB_PURGE_AGE=1d
      - F2B_IPTABLES_CHAIN=INPUT
