# -*- mode: ruby -*-
# vi: set ft=ruby :
# Can be configured with GIT_REVISION, ANSIBLE_TAGS,ANSIBLE_PLAYBOOK env variables
# eg.
# > GIT_REVISION=master run-setup-playbook-tests.sh
# > ANSIBLE_TAGS=flux run-setup-playbook-tests.sh
Vagrant.configure(2) do |config|

  config.vm.box = "ubuntu/bionic64"
  config.vm.network :forwarded_port, guest: 80, host: 8080
  config.vm.network :forwarded_port, guest: 433, host: 8433
  config.vm.network :forwarded_port, guest: 21, host: 2121
  for i in 21100..21110
    config.vm.network :forwarded_port, guest: i, host: i
  end

  config.vm.provider :virtualbox do |vm|
    vm.name = "flux.dev"
    vm.memory = 2048
    vm.cpus = 2
  end

  config.vm.provision :shell, inline: "apt-get install -y python" #Because Ansible needs python 2
  config.vm.provision :ansible do |ansible|

    ansible.playbook = "../#{ENV['ANSIBLE_PLAYBOOK']}.yml"

    raw_arguments = []
    raw_arguments.push("--extra-vars=update_sshd_config=false")
    raw_arguments.push("--extra-vars=dns_name=localhost")
    raw_arguments.push("--extra-vars=git_revision=#{ENV['GIT_REVISION']}")

    if ENV['ANSIBLE_TAGS']
      raw_arguments.push("--tags=#{ENV['ANSIBLE_TAGS']}")
    end

    ansible.raw_arguments = raw_arguments
  end
end
