# Worflow pour CI des commandes Yarn
name: CI - Deploy on develop / recette

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out the repository
      - uses: actions/checkout@v2

      # Install dependencies
      - name: Deploy App
        run: |
          cd ../template-apprentissage-infra/script
          bash echo-deploy.sh recette
