# Worflow pour CI des commandes Yarn
name: Yarn CI

on: [push]

jobs:
  # Single job
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out the repository
      - uses: actions/checkout@v2

      # Install dependencies
      - name: Run Yarn Install
        run: |
          cd server
          yarn install

      # Lint
      - name: Run Lint
        run: |
          cd server
          yarn lint

      # Run mocha tests
      - name: Run Tests
        run: |
          cd server
          yarn test
